######################################################################
# Automatically generated by qmake (3.0) ?? 11? 5 05:03:35 2017
######################################################################

TEMPLATE = app
TARGET = snake
INCLUDEPATH += .
QT += widgets
QT += gui core

# Input
HEADERS += snakedlg.h ui_snakedlg.h
FORMS += snakedlg.ui
SOURCES += main.cpp snakedlg.cpp
RESOURCES += showpics.qrc
